{{- if .Values.createRBAC }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "opentelemetry-operator.name" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "opentelemetry-operator.name" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ template "opentelemetry-operator.name" . }}-controller-manager
    namespace: {{ template "opentelemetry-operator.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "opentelemetry-operator.name" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "opentelemetry-operator.name" . }}-proxy-role
subjects:
  - kind: ServiceAccount
    name: {{ template "opentelemetry-operator.name" . }}-controller-manager
    namespace: {{ template "opentelemetry-operator.namespace" . }}
{{- end }}
