{{- if .Values.createRBAC }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "opentelemetry-operator.name" . }}-leader-election-rolebinding
  namespace: {{ template "opentelemetry-operator.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "opentelemetry-operator.name" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ template "opentelemetry-operator.name" . }}-controller-manager
    namespace: {{ template "opentelemetry-operator.namespace" . }}
{{- end }}
